project:
  type: website
  output-dir: docs

website:
  title: "Kimaya D. Lacey, B.S"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Education.qmd
        text: Education
      - href: Resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: Contact.qmd
        text: Contact
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

